### ISSUE TITLE
When the query range is large, data is incomplete

### ISSUE THREAD

**Issue by hashwing** [pwillie/prometheus-es-adapter#11]
For example, when the query data exceeds 1000, the data is incomplete

https://github.com/pwillie/prometheus-es-adapter/blob/7abcf6d7ba16bb551c5de61542bd35b42898aaa3/lib/elasticsearch/adapter.go#L252

**Comment by pwillie** [comment]
Hi @hashwing,

Thanks for the report.  Will take a look.

**Comment by pwillie** [comment]
Have created command line param -es_search_max_docs or env var ES_SEARCH_MAX_DOCS to set maximum search results returned.  Will default to 1000 so default behaviour has not changed.

Docker image available at `pwillie/prometheus-es-adapter:latest`.  Please give it a go and let me know how you get on.

**Comment by hashwing** [comment]
Thanks. Then I have a question. if you need to query data for a month or even a year, the amount of data is large, what good idea?

**Comment by pwillie** [comment]
I would be inclined to setup a tiered Prometheus configuration and use recording rules reduce the granularity for long term storage.

**Comment by hashwing** [comment]
Thanks. It has run in kubernetes.
