### ISSUE TITLE
ES adaptor error

### ISSUE THREAD

**Issue by lgarvey** [pwillie/prometheus-es-adapter#15]
I'm wondering if you have seen this error before? 

The cluster health is green and I've pasted the configuration below.

{
    "level": "error",
    "ts": 1529502515.7707772,
    "caller": "elasticsearch/adapter.go:171",
    "msg": "&{Index:active-prom-metrics-000010 Type:sample Id:AWQddEG6m4rmyDBXOv-d Version:0 Status:403 Result: ForcedRefresh:false Found:false Error:0xc424804000}",
    "stacktrace": "github.com/pwillie/prometheus-es-adapter/lib/elasticsearch.(*Adapter).after\n\t/gopath/src/github.com/pwillie/prometheus-es-adapter/lib/elasticsearch/adapter.go:171\ngithub.com/pwillie/prometheus-es-adapter/lib/elasticsearch.(*Adapter).(github.com/pwillie/prometheus-es-adapter/lib/elasticsearch.after)-fm\n\t/gopath/src/github.com/pwillie/prometheus-es-adapter/lib/elasticsearch/adapter.go:86\ngithub.com/pwillie/prometheus-es-adapter/vendor/gopkg.in/olivere/elastic%2ev5.(*bulkWorker).commit\n\t/gopath/src/github.com/pwillie/prometheus-es-adapter/vendor/gopkg.in/olivere/elastic.v5/bulk_processor.go:506\ngithub.com/pwillie/prometheus-es-adapter/vendor/gopkg.in/olivere/elastic%2ev5.(*bulkWorker).work\n\t/gopath/src/github.com/pwillie/prometheus-es-adapter/vendor/gopkg.in/olivere/elastic.v5/bulk_processor.go:455"
}

# Configuration:
      {
        "name": "ES_WORKERS",
        "value": "4"
      },
      {
        "name": "ES_BATCH_COUNT",
        "value": "-1"
      },
      {
        "name": "ES_BATCH_SIZE",
        "value": "-1"
      },
      {
        "name": "ES_BATCH_INTERVAL",
        "value": "30"
      }
    ]

# /_cat/indices/
green open active-prom-metrics-000009 NSEg2stlQ1iuc0LCjpvFnw 5 1   2906642 0 481.5mb 240.2mb
green open active-prom-metrics-000010 2fAYWtJ4TyqX-eej4C8VdA 5 1     91669 0  16.1mb   8.1mb
green open active-prom-metrics-000005 hILga_fPT1uWQ8aSffPz6w 5 1  71975632 0  11.7gb   5.8gb
green open active-prom-metrics-000004 av9pCqRZT5-8XE0Znnr12g 5 1   1311229 0 322.4mb 161.1mb
green open active-prom-metrics-000007 ktHKZUqWTlOJ-QrED17dNw 5 1 306499652 0    51gb  25.5gb
green open active-prom-metrics-000002 UgW6iJWXR5ugQO1ljf6cxw 5 1   1711442 0 434.1mb   217mb
green open active-prom-metrics-000006 6zxdnZmdTICD7LYZNLSX7Q 5 1  11697447 0   1.8gb 972.1mb
green open .kibana                    tRt2Pa75TKy_nWKUAmmqeA 1 1         1 0   6.4kb   3.2kb
green open active-prom-metrics-000008 wA6OFk6IRceG5BzkVDxyVA 5 1   1428027 0 237.7mb 118.8mb
green open active-prom-metrics-000001 bD4S9wclQ_2DTBIXJSCo6w 5 1   6047185 0   1.1gb 602.9mb
green open active-prom-metrics-000003 Dc46BL4XTBuhn6reKN66Vg 5 1   1042120 0 265.3mb 132.7mb

**Comment by pwillie** [comment]
Am not sure in this case but the 403 is indicating that there is a permission issue.  Have just been making some changes that should shed some more light on issues like this.

**Comment by pwillie** [comment]
@lgarvey, just wondering if this is still an issue for you?

**Comment by lgarvey** [comment]
Hi @pwillie I'm not sure.  We're running prom without long term storage but reenabling this module is on my to do list.  However, I'm assuming the problem was caused by me, due to incorrectly configuring the prom storage volume.  I'll close this issue for now.
