### ISSUE TITLE
Add possibility for a daily index (only)

### ISSUE THREAD

**Issue by Kanshiroron** [pwillie/prometheus-es-adapter#23]
Hello,
Indexes names are not convenient to use, and impossible to manage automatic deletion (based on the index age, with elastic curator).
The idea would be to include the date in the index name (i.e.: `metrics-2019.05.27`), as this is the most widely used pattern.
In that case, following options shouldn't be taken into account: `ES_INDEX_MAX_AGE`, `ES_INDEX_MAX_DOCS` and `ES_INDEX_MAX_SIZE`.

**Comment by pwillie** [comment]
Hi @Kanshiroron,

Thanks for the feedback.  Sounds like a reasonable use case.

**Comment by Kanshiroron** [comment]
Hey @pwillie,
I'm willing to contribute if you like. Just point out the file.

**Comment by pwillie** [comment]
Thanks for the offer but am testing a fix now.

**Comment by Kanshiroron** [comment]
Awesome!
Since you are working on this part, I noticed that one of the es-adapter I deployed was throwing errors if the index was already created (I have multiple Prometheus instances forwarding metrics to the same ES index).
I have restarted the es-adapter since so I'm missing the log, but I'll update this ticket if I notice it again.

**Comment by pwillie** [comment]
New image is available at `pwillie/prometheus-es-adapter:v6`.  Note the new boolean flag `es_index_daily` with default value `false` to keep current default behaviour.

Please let me know how you go so we can close this issue.

**Comment by Kanshiroron** [comment]
Awesome, thanks a lot for your reactivity. I'll test it shortly and give you updates as soon as I have some.
Thanks again!
