### ISSUE TITLE
License for prometheus-es-adapter

### ISSUE THREAD

**Issue by gevanoff** [pwillie/prometheus-es-adapter#7]
Hi Peter,
We're looking at using the prometheus-es-adapter but have noted that no license has been indicated in the README.md or in a separate license file. Am I missing it somewhere else, or has none been selected yet?
Thanks,
-g

**Comment by gevanoff** [comment]
Hey @pwillie, I hope you have a chance sometime soon to comment on this or to add a license. If it's too immature in its current development state, I understand that too.

**Comment by pwillie** [comment]
Hi @gevanoff,

Glad to hear of your interest in this project.  Will add a license shortly.
