### ISSUE TITLE
[Question] Clustered prometheus pollers using this adapter

### ISSUE THREAD

**Issue by sevagh** [pwillie/prometheus-es-adapter#8]
Hello. First of all thanks for writing and releasing this with a friendly license.

In my setup, I have 3 identical Prometheus pollers set up to be HA. If I have all 3 of them configured to use this remote storage adapter, from what I've heard Prometheus doesn't do any remote-storage outgoing call deduplication.

Do we depend on Elastic's behavior for receiving identical timeseries? Will Elastic create 3 separate timeseries if all 3 pollers send the same data? Have you tested that case? Any suggestions?

Thanks.

**Comment by pwillie** [comment]
Hi @sevagh,

I haven't actually gone down that path yet so wont be of much help here sorry.  If you come up with anything would be great if you posted back your results/findings.

Sorry I couldn't help you on this one.

**Comment by sevagh** [comment]
So I activated the adapter on all of the HA pollers. It runs fine - I think the result is increasing the data granularity, but not affecting the data integrity.
